This check-in results in a medium-sized change to the start_test script: it eliminates the -onetest and -startdir flags and supports an arbitrary number of command-line arguments that will represent directories (determined by -d and -x tests) and files (determined by -r and not being a directory) to test.
As before, directories are tested recursively by default
unless the -norecurse flag is used.

If no directories or files are provided, the directory
list is assumed to be "." (which is to say, using
"start_test" with traditional flags other than -startdir
and -onetest will work as before).

Irrespective of the order they are provided on the
command line, all files are tested before any directories.
The files and directories themselves are tested in the
order specified.

This check-in also updates any scripts that I could find
that use the -onetest or -startdir flags with start_test.
It's likely that I've missed some, so check for any that
you particularly like.  Also, if you own any cron jobs,
please check to make sure that they don't rely on these
flags (or check tomorrow to ensure that all your cron
jobs have run and returned the right number of successes).

This change does not include the change that we discussed
after today's meeting to allow start_test to be run from
arbitrary directories.  That will come in a distinct checkin.


git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@13078 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/test/start_test b/test/start_test
--- a/test/start_test
+++ b/test/start_test
@@ -8,13 +8,14 @@
 #
 # Executive Summary: The overall flow of the testing system is that it
 # will recursively descend into subdirectories looking for Chapel
-# programs to compile and run (*.chpl) as well as for other tests to
-# run (sub_test).  The output of these runs will typically be logged
-# in a file stored in the Logs/ subdirectory, as will a summary of the
+# programs to compile and run (*.chpl), Makefile-driven tests (USEMAKE
+# file + Makefile with 'test' target), and other tests to run
+# (sub_test).  The output of these runs will typically be logged in a
+# file stored in the Logs/ subdirectory, as will a summary of the
 # errors reported (determined by grepping for the string "[Error", so
 # don't have your program print this out) and the status of "future"
-# tests -- those that have never worked, but are checked in for the
-# purpose of sharing and placeholding.
+# tests -- those that are not expected to work, but are checked in for
+# the purpose of sharing and staking out future work.
 #
 # Here's the directory structure:
 #
@@ -25,7 +26,7 @@
 #   Samples/ -- sample tests go here; these are for illustration only
 #               and won't be run by default.  To try running the
 #               test system against these samples, use:
-#                      start_test -startdir ./Samples
+#                      start_test ./Samples
 #   Share/   -- a place to put codes to share with other developers.
 #               These will not be run by default.
 #   */       -- all other directories will contain tests
@@ -37,14 +38,14 @@
 #
 #   option     argument               default value
 #   ---------  ---------------------  -------------
+#              [list of directories]  .
+#              [list of tests]        ""
 #   -compiler  <compiler executable>  ../bin/<platform>/chpl
 #   -compopts  <option list>          ""
 #   -execopts  <option list>          ""
 #   -launchcmd <launcher command>     ""
-#   -startdir  <test subdir>          .
 #   -norecurse
 #   -componly
-#   -onetest   <single test>          N/A
 #   -logfile   <log filename>         ./Logs/<username>.<platform>.log
 #   -valgrind
 #   -notee
@@ -55,8 +56,16 @@
 #   -suppress <suppression file>
 #   -interpret (DEPRECATED)
 #
-# These options can be used with a double-dash as well 
+# All options can be used with a double-dash format as well 
 # (e.g. --compopts).
+#
+# The main arguments to start_test are a list of directories and/or
+# list of files that should be tested.  The test system will test all
+# of the files listed and then all of the directories, including their
+# children (unless the -norecurse flag is used).  If no list of
+# directories or files is provided, "." is used as the starting
+# directory (i.e., all subdirectories of the current directory will be
+# tested.
 #
 # The -compiler option allows the user to specify the compiler to test
 # if it is something other than the obvious one in the current CVS
@@ -66,7 +75,7 @@
 # The -compopts option allows the user to specify a set of compiler
 # options that should be used on every invocation to the compiler.
 # Additional compiler options can be specified on a directory-by-
-# directory basis.
+# directory basis using mechanisms described below (COMPOPTS/.compopts).
 #
 # The -componly option specifies that this testing run should only
 # be compiled and not executed; this causes success of a test to
@@ -78,30 +87,21 @@
 # with compiler options, these can be ammended in each subdirectory.
 #
 # The -launchcmd option allows the user to specify a program launch
-# utility to use to start generated executables. When tests are executed
-# the launchcmd is prepended to the command line used. This allows for
-# example for a binary generated by a cross compiler to be copied over to
-# the target machine before it is executed.
+# utility to use to start generated executables. When tests are
+# executed, the launchcmd is prepended to the command line used. This
+# allows, for example, for a binary generated by a cross compiler to
+# be copied over to the target machine before it is executed.
 #
-# The -startdir option allows the user to specify a subdirectory of
-# the testing system to start in (and limit itself to).  Assuming
-# that tests are sorted into subdirectories by useful features, this
-# allows you to run a subset of the tests easily.
-#
-# The -norecurse flag requests that the starting directory be tested
-# but that its subdirectories not be visited recursively.  This is
-# useful for pinpointing the testing of a single directory with
-# -startdir when you do not want to also visit its subdirectories,
-# if any.
-#
-# The -onetest flag requests that only a single test be tested.  The
-# test should be a full path to the test, and should have a .chpl file
-# extension.
+# The -norecurse flag requests that the listed directories be tested
+# but that no subdirectories be visited recursively.  This is useful
+# for pinpointing the testing of a single directory when you do not
+# want to test any of its subdirectories.
 #
 # The -logfile option indicates where the log of the test run should
-# be kept.  By default it's based on the user's name.  At the end of
-# the run, a second log file named <logfile>.summary will be generated
-# containing only the Errors and future tests that were logged.
+# be kept.  By default it's based on the user's name and the platform
+# you're testing.  At the end of the run, a second log file named
+# <logfile>.summary will be generated containing only the Errors and
+# future tests that were logged.
 #
 # A -suppress option can be used to specify a file listing tests that
 # should be ignored for a particular run if they fail (and an error
@@ -177,6 +177,9 @@
 # will be skipped when using "none" as the communic layer (either
 # explicitly or by not specifying a -comm flag).
 #
+#
+# STRUCTURE OF TEST DIRECTORIES
+#
 # By default, setting up a subdirectory for testing simply consists
 # of creating the directory, putting Chapel (.chpl) source files
 # into it and an expected output file (.good) for each source file
@@ -190,7 +193,7 @@
 # errors, warnings, and correct programs to all be tested using the
 # same mechanisms.  
 #
-#If the output for a test varies by machine, communication layer, or
+# If the output for a test varies by machine, communication layer, or
 # platform name, files named <testname>.<machname>.good,
 # <testname>.comm-<commlayer>.good, or <testname>.<platform>.good can
 # be used to specify the output for such tests, where "machname" is
@@ -360,12 +363,12 @@
 # Again, to see a sample run of the testing system, look through
 # the Samples/ directory, then run:
 #
-#     ./start_test -startdir Samples
+#     ./start_test Samples
 #
 # and inspect the Samples/ and Logs/ subdirectories to see what
 # was generated.  Then use:
 #
-#     ./start_clean -startdir Samples
+#     ./start_clean Samples
 #
 # to clean back up again.
 #
@@ -409,9 +412,8 @@ set execopts = ""
 set compiler = ""
 set compopts = ""
 set launchcmd = ""
-set startdir = "$testdir"
-set onetest = ""
-set onetestpath = ""
+set dirlist = ""
+set testlist = ""
 set logfile = "$testdir/Logs/$user.$platform.log"
 set valgrind = 0
 set valgrindexe = 0
@@ -450,12 +452,6 @@ while ( $#argv > 0 )
 	case --compopts:
 		shift
 		set compopts = "$argv[1]"
-		shift
-		breaksw
-	case -startdir:
-	case --startdir:
-		shift
-		set startdir = $argv[1]
 		shift
 		breaksw
 	case -logfile:
@@ -500,14 +496,6 @@ while ( $#argv > 0 )
 		shift
 		setenv CHPL_COMPONLY true
 		breaksw
-        case -onetest:
-        case --onetest:
-                shift
-                set onetestpath = $argv[1]
-                set testfutures = 1
-                set testnotests = 1
-                shift
-                breaksw
         case -valgrindexe:
         case --valgrindexe:
                 shift
@@ -542,8 +530,6 @@ while ( $#argv > 0 )
 		echo "          -compopts" \"\"
 		echo "          -execopts" \"\"
                 echo "          -launchcmd" \"\"
-                echo "          -onetest"
-		echo "          -startdir ."
                 echo "          -norecurse"
 		echo "          -componly"
                 echo "          -performance"
@@ -560,7 +546,19 @@ while ( $#argv > 0 )
 		exit 0
 		breaksw
 	default:
-		echo \[ERROR: Unknown command line parameter \"$argv[1]\", aborting.\]
+                if ( -d "$argv[1]" && -x "$argv[1]") then
+                    echo "$argv[1] is a directory"
+                    set dirlist = "$dirlist $argv[1]"
+                    shift
+                    breaksw
+                else if ( -r "$argv[1]") then
+                    echo "$argv[1] is a file"
+                    set testlist = "$testlist $argv[1]"
+                    shift
+                    breaksw
+                else
+                    echo \[ERROR: Unknown command line parameter \"$argv[1]\", aborting.\]
+                    shift
 		exit 1
 		breaksw
 	endsw
@@ -644,40 +642,27 @@ else
     echo \[numlocales: \"$numlocales\"\] |& tee -a $logtmp
 endif
 
-if ($onetestpath != "") then
-    if ($startdir != $testdir) then
-        echo \[Using -startdir with -onetest doesn\'t make sense\] |& $tee -a $logtmp
-        exit 1
-    endif
-    if ( -r "$onetestpath") then
-        set startdir = `dirname $onetestpath`
-        set onetest = `basename $onetestpath`
-        set recurse = 0
-    else
-        echo \[Can\'t access test: \"$onetestpath\"\] |& $tee -a $logtmp
-        exit 1
-    endif
+if ("$dirlist" == "" && "$testlist" == "") then
+    set dirlist = "."
 endif
 
-# if startdir exists then get absolute path name for
-if ( -d "$startdir" && -x "$startdir" ) then
-	pushd "$startdir" >& /dev/null
-	set startdir = "$cwd"
-	popd >& /dev/null
+# get absolute path for each directory
+set absdirs = ""
+foreach dir ($dirlist)
+    pushd "$dir" >& /dev/null
+    set currentdir = "$cwd"
+    popd >& /dev/null
 
-        if ($recurse == 1) then
-            echo \[startdir: \"$startdir\"\] |& $tee -a $logtmp
-        else
-            echo \[startdir \(nonrecursive\): \"$startdir\"\] |& $tee -a $logtmp
-            if ($onetest != "") then
-                echo \[onetest: $onetest\] |& $tee -a $logtmp
-            else
-            endif
-        endif
+    set absdirs = "$absdirs $currentdir"
+end
+
+
+echo \[tests: \"$testlist\"] |& $tee -a $logtmp
+
+if ($recurse == 1) then
+    echo \[directories: \"$absdirs\"] |& $tee -a $logtmp
 else
-	echo \[Permission denied for starting directory: \"$startdir\"\] \
-		|& $tee -a $logtmp
-	exit 1
+    echo \[directories: \(nonrecursive\): \"$absdirs\"] |& tee -a $logtmp
 endif
 
 #if logfile directory exists, then get absolute path for
@@ -704,29 +689,6 @@ endif
 mv $logtmp $logfile
 
 
-# if specified to start in a specific directory, start there
-set basedir = $testdir
-if ( $startdir != $cwd ) then
-	set basedir = $startdir
-	cd $basedir
-endif
-
-# execute script that is located in each directory
-#   Recursively list all directories (have a : in the line)
-#   Don't include output or RCS directories (-v says don't include)
-#   Take off : with sed
-#
-if ($recurse == 1) then
-    set dirs = `ls -R |& grep ":" | grep -v "\.:" | grep -v "Permission denied" | grep -v "CVS" | grep -v Bin | grep -v Logs | grep -v Samples | grep -v Share | grep -v perfdat | sed 's/://g'`
-    # gotta add ./ on in case -startdir is specified
-    set dirs = (./ $dirs)
-else
-    set dirs = (./)
-endif
-
-#echo "dirs is $dirs"
-#echo "cwd is $cwd"
-#exit 0
 
 if ($testfuturesonly == 1) then
     setenv CHPL_TEST_FUTURES 2
@@ -744,6 +706,63 @@ else
     setenv CHPL_TEST_NOTESTS 0
 endif
 
+foreach test ($testlist)
+    set basedir = `dirname $test`
+    set testname = `basename $test`
+    set recurse = 0
+
+    pushd $basedir >& /dev/null
+    echo " " |& $tee -a $logfile
+    echo "[Working on file $test]" |& $tee -a $logfile
+
+    set sub_test = $testdir/Bin/sub_test
+    if (-x ./sub_test) then
+        set sub_test = ./sub_test
+    else
+	set sub_test = $testdir/Bin/sub_test
+    endif
+
+    if (-x ./Bin/sub_clean) then
+        set sub_clean = ./Bin/sub_clean
+    else
+        set sub_clean = $testdir/Bin/sub_clean
+    endif
+    setenv COMPOPTS "$compopts"
+    setenv EXECOPTS "$execopts"
+    setenv NUMLOCALES "$numlocales"
+    setenv LAUNCHCMD "$launchcmd"
+    setenv CHPL_ONETEST "$testname"
+    echo "[Starting $sub_test `date`]" |& $tee -a $logfile
+
+    $sub_clean "$testdir" |& $tee -a $logfile
+    $sub_test "$compiler" "$testdir" |& $tee -a $logfile
+
+    unsetenv CHPL_ONETEST
+
+    popd >& /dev/null
+end
+
+foreach absdir ($absdirs)
+# if specified to start in a specific directory, start there
+    set basedir = $testdir
+    if ( $absdir != $cwd ) then
+	set basedir = $absdir
+	cd $basedir
+    endif
+
+# execute script that is located in each directory
+#   Recursively list all directories (have a : in the line)
+#   Don't include directories known not to be for tests
+#   Take off : with sed
+#
+    if ($recurse == 1) then
+        set dirs = `ls -R |& grep ":" | grep -v "\.:" | grep -v "Permission denied" | grep -v "CVS" | grep -v Bin | grep -v Logs | grep -v Samples | grep -v Share | grep -v perfdat | sed 's/://g'`
+# gotta add ./ on in case explicit start directories were specified
+        set dirs = (./ $dirs)
+    else
+        set dirs = (./)
+    endif
+
 foreach dir ($dirs)
 	cd $basedir
 	if ( -x $dir ) then
@@ -757,8 +776,12 @@ foreach dir ($dirs)
 			$tee -a $logfile
 		continue
 	endif
+
        	echo " " |& $tee -a $logfile
+        echo "[Working on directory $dir]" |& $tee -a $logfile
+
 	set numtests = `(ls *.{chpl,v} |& grep -v "No match" | wc -l)`
+
 
         if (-e ./NUMLOCALES && $CHPL_COMM == "none") then
             echo \[Skipping NUMLOCALES directory: $dir \] |& $tee -a $logfile
@@ -766,8 +789,7 @@ foreach dir ($dirs)
         endif
 
 	if ((! -e ./NOTEST && ($numtests != 0 || -x ./sub_test) && \
-            (($CHPL_TEST_INTERP == "off") || (! -e ./NOINTERP && ! -e ./NOEXEC && ! -e ./EXECOPTS))) \
-            || $onetest != "") then
+            (($CHPL_TEST_INTERP == "off") || (! -e ./NOINTERP && ! -e ./NOEXEC && ! -e ./EXECOPTS)))) then
 		if (-x ./sub_test) then
 		    set sub_test = ./sub_test
 		else
@@ -782,16 +804,15 @@ foreach dir ($dirs)
 		setenv EXECOPTS "$execopts"
                 setenv NUMLOCALES "$numlocales"
                 setenv LAUNCHCMD "$launchcmd"
-                if ($onetest != "") then
-                    setenv CHPL_ONETEST "$onetest"
-                endif
 		echo "[Starting $sub_test `date`]" |& $tee -a $logfile
+
 		$sub_clean "$testdir" |& $tee -a $logfile
 		$sub_test "$compiler" "$testdir" |& $tee -a $logfile
 	else
 		echo \["No tests in directory " $dir\] |& \
 			$tee -a $logfile
 	endif
+end
 end
 
 # return to directory where we started and remove lock
