use a venv
Signed-off-by: Jade Abraham <jade.abraham@hpe.com>

diff --git a/test/studies/arkouda/sub_test b/test/studies/arkouda/sub_test
--- a/test/studies/arkouda/sub_test
+++ b/test/studies/arkouda/sub_test
@@ -98,12 +98,20 @@ else
 fi
 
 if [ ${CHPL_TEST_ARKOUDA_STOP_AFTER_BUILD} = "false" ]; then
-  # Install Arkouda and python dependencies to a python-deps subdir
-  export PYTHONUSERBASE=$ARKOUDA_HOME/python-deps
-  # If Arkouda deps use any of our test deps, try to use the versions we want
+
+    # If Arkouda deps use any of our test deps, try to use the versions we want
   AK_PIP_CONTRAINTS="--constraint $CHPL_HOME/third-party/chpl-venv/test-requirements.txt"
   log "Installing Arkouda using python3 at: $(which python3)"
-  if ! python3 -m pip install --force-reinstall --timeout 60 $AK_PIP_CONTRAINTS -e .[dev] --user ; then
+  # create a virtual environment for running the tests
+  # if one was already created and set in CHPL_TEST_VENV_DIR, use it
+  if [ -n "$CHPL_TEST_VENV_DIR" ] && [ "$CHPL_TEST_VENV_DIR" != "none" ]; then
+    source $CHPL_TEST_VENV_DIR/bin/activate
+  else
+    python3 -m venv .venv
+    source .venv/bin/activate
+  fi
+
+  if ! python3 -m pip install --force-reinstall --timeout 60 $AK_PIP_CONTRAINTS -e .[dev] ; then
     log_fatal_error "installing arkouda"
   fi
 
@@ -175,6 +183,15 @@ if [ ${CHPL_TEST_ARKOUDA_STOP_AFTER_BUILD} = "false" ]; then
     fi
     test_end
   fi
+
+  # deactivate the venv and cleanup
+  if [ -n "$CHPL_TEST_VENV_DIR" ] && [ "$CHPL_TEST_VENV_DIR" != "none" ]; then
+    deactivate
+  else
+    deactivate
+    rm -rf .venv
+  fi
+
 else
   # If we've gotten here then the build succeeded I need to create a "fake"
   # test for Jenkins even though in this mode all I really care about is the
