Updated bundled GASNet to GASNet-2025.2.0-snapshot
Signed-off-by: John H. Hartman <jhh67@users.noreply.github.com>

diff --git a/third-party/gasnet/gasnet-src/Makefile.in b/third-party/gasnet/gasnet-src/Makefile.in
--- a/third-party/gasnet/gasnet-src/Makefile.in
+++ b/third-party/gasnet/gasnet-src/Makefile.in
@@ -349,15 +349,13 @@ GASNET_PSHM_CFLAGS = @GASNET_PSHM_CFLAGS@
 GASNET_PSHM_ENABLED = @GASNET_PSHM_ENABLED@
 GASNET_PSHM_LDFLAGS = @GASNET_PSHM_LDFLAGS@
 GASNET_PSHM_LIBS = @GASNET_PSHM_LIBS@
+GASNET_SMP_SPAWNER_CONF = @GASNET_SMP_SPAWNER_CONF@
 GASNET_THREAD_DEFINES = @GASNET_THREAD_DEFINES@
 GASNET_THREAD_LIBS = @GASNET_THREAD_LIBS@
 GASNET_UCX_SPAWNER_CONF = @GASNET_UCX_SPAWNER_CONF@
 GASNET_UDP_LIBS = @GASNET_UDP_LIBS@
 GDB_PATH = @GDB_PATH@
 GMAKE = @GMAKE@
-GNI_CFLAGS = @GNI_CFLAGS@
-GNI_LDFLAGS = @GNI_LDFLAGS@
-GNI_LIBS = @GNI_LIBS@
 GREP = @GREP@
 GSTACK_PATH = @GSTACK_PATH@
 HAVE_INTTYPES_H = @HAVE_INTTYPES_H@
@@ -367,6 +365,7 @@ HIP_CFLAGS = @HIP_CFLAGS@
 HIP_LDFLAGS = @HIP_LDFLAGS@
 HIP_LIBS = @HIP_LIBS@
 HIP_guess_prog = @HIP_guess_prog@
+HUGETLBFS_guess_prog = @HUGETLBFS_guess_prog@
 HWLOC_CFLAGS = @HWLOC_CFLAGS@
 HWLOC_LDFLAGS = @HWLOC_LDFLAGS@
 HWLOC_LIBS = @HWLOC_LIBS@
@@ -543,7 +542,6 @@ CONDUITMODE_DIST_SUBDIRS = \
 	udp-conduit  		\
 	ibv-conduit 		\
 	ucx-conduit 		\
-	aries-conduit           \
 	ofi-conduit
 
 CONDUITMODE_headers = \
@@ -1366,15 +1364,25 @@ check tests-clean:
 	@$(MAKE) $(recurse_local) DO_WHAT=$@
 	@cd "$(top_builddir)/other" && $(MAKE) $@
 
-install-data-local: 
+check-prefix-vars: force
 	@if test -n "$(DESTDIR)" -a `expr "X$(DESTDIR)" : X/` = 0; then \
-          echo "ERROR: \$$DESTDIR must begin with a '/' character."; \
+          echo "ERROR: install \$$DESTDIR must begin with a '/' character."; \
+	  exit 1; \
+	 fi
+	@if test -n "$(DESTDIR)" -a `expr "$(DESTDIR)" : ".*[[:space:]]"` != 0; then \
+          echo "ERROR: install \$$DESTDIR must not contain space characters."; \
 	  exit 1; \
 	 fi
 	@if test `expr "X$(prefix)" : X/` = 0; then \
-          echo "ERROR: \$$prefix must begin with a '/' character."; \
+          echo "ERROR: install \$$prefix must begin with a '/' character."; \
 	  exit 1; \
 	 fi
+	@if test `expr "$(prefix)" : ".*[[:space:]]"` != 0; then \
+          echo "ERROR: install \$$prefix must not contain space characters."; \
+	  exit 1; \
+	 fi
+
+install-data-local: check-prefix-vars
 	@$(MAKE) $(recurse_local) DO_WHAT=install-data
 	@$(MAKE) recurse_special DO_WHAT=install-data
 	$(mkinstalldirs) $(DESTDIR)$(docdir)
@@ -1406,15 +1414,7 @@ install-data-local:
             chmod 644 "$$destpc" || exit $$? ; \
           else :; fi; \
         done
-install-exec-local:
-	@if test -n "$(DESTDIR)" -a `expr "X$(DESTDIR)" : X/` = 0; then \
-          echo "ERROR: \$$DESTDIR must begin with a '/' character."; \
-	  exit 1; \
-	 fi
-	@if test `expr "X$(prefix)" : X/` = 0; then \
-          echo "ERROR: \$$prefix must begin with a '/' character."; \
-	  exit 1; \
-	 fi
+install-exec-local: check-prefix-vars
 	@$(MAKE) $(recurse_local) DO_WHAT=install-exec
 	@$(MAKE) recurse_special DO_WHAT=install-exec
 uninstall-local: 
