Upgrade to GASNet-EX 2021.3.0
This includes significant performance and scalability improvements for
InfiniBand networks when using dynamic registration (our default mode),
a powerpc race fix (previously patched in 17083), and improvements to
the ssh spawner. There's also initial support for "Memory Kinds" to
support communication using non-host memory (e.g. GPUs). The ofi
conduit has also been re-added though is currently experimental.

For the full changelog see: https://gasnet.lbl.gov/dist-ex/ChangeLog

InfiniBand performance is significantly improved by increasing the
number of memory registration entries and increasing the size of the
hash table used to track registration entries. This will improve some
long-standing performance issues for applications that communicate a
large fraction of memory like ISx and NPB-FT as well as applications
that increase the amount of communicated regions as scale increases like
Arkouda. https://bitbucket.org/berkeleylab/gasnet/pull-requests/433 has
more detail on this specific effort. I'm expecting large improvements
for array copies and ISx/NPB-FT. 16-node-cs-hdr performance results:

Array copy performance (PUTs)

| config | 1 MiB        | 1 GiB        | 48 GiB      |
| ------ | -----------: | -----------: | ----------: |
| before | ~10500 MiB/s |  ~4000 MiB/s | ~1450 MiB/s |
| after  | ~10500 MiB/s | ~11700 MiB/s | ~3250 MiB/s |

ISx/NPB-FT:

| config | ISx | NPB-FT     |
| ------ | --: | ---------: |
| before | 50s | 115 GFLOPS |
| after  | 10s | 430 GFLOPS |

Resolves private 1411
Helps 14438
Helps 14439
Helps Private 1792
Helps Private 1819

Signed-off-by: Elliot Ronaghan <ronawho@gmail.com>

diff --git a/third-party/gasnet/gasnet-src/Makefile.am b/third-party/gasnet/gasnet-src/Makefile.am
--- a/third-party/gasnet/gasnet-src/Makefile.am
+++ b/third-party/gasnet/gasnet-src/Makefile.am
@@ -34,6 +34,7 @@ CONDUITMODE_headers = 		\
 	gasnet_ammacros.h  	\
 	gasnet_trace.h     	\
 	gasnet_fwd.h    	\
+	other/kinds/gasnet_mk.h \
 	extended-ref/coll/gasnet_coll.h \
 	extended-ref/ratomic/gasnet_ratomic.h \
 	extended-ref/vis/gasnet_vis.h      
@@ -370,8 +371,12 @@ dist-hook:
            exit 1 ; \
         fi
 	if test -d $(srcdir)/.git ; then \
-	  GASNET_DESC=`$${GIT=git} --git-dir=$(srcdir)/.git describe` || exit $$? ; \
-	  $(PERL) -pi -e "s:no-version-control-info:$$GASNET_DESC:;" -- $(distdir)/configure $(distdir)/gasnet_tools.c || exit $$? ; \
+	  GASNET_DESC=`( cd $(srcdir) && $${GIT=git} describe --long --dirty --always ) 2>/dev/null | head -n 1`; \
+	  if test -z "$$GASNET_DESC"; then \
+	    echo 'Use of git describe failed even though .git exists' 1>&2; \
+	    exit 1;                        \
+	  fi;                              \
+	  $(PERL) -pi -e "s:no-version-control-info:$$GASNET_DESC:;" -- $(distdir)/configure || exit $$? ; \
 	  echo $$GASNET_DESC > $(distdir)/version.git || exit $$? ; \
 	fi
 	if test -f $(distdir)/docs/Makefile ; then \
