Add helpful error message when curl fails
Also stop using $(PYTHON)

diff --git a/third-party/chpl-venv/Makefile b/third-party/chpl-venv/Makefile
--- a/third-party/chpl-venv/Makefile
+++ b/third-party/chpl-venv/Makefile
@@ -30,16 +30,20 @@ $(CHPL_VENV_INSTALL_DIR):
 
 # Install pip via get-pip.py to ensure we have an updated version
 $(PIP): $(CHPL_VENV_INSTALL_DIR)
-	if [ -z "$$CHPL_PIP" ]; then \
-	  (cd install && curl -O $(GETPIP) && \
+	@echo "Installing local copy of pip with get-pip.py from $(GETPIP)"
+	@if [ -z "$$CHPL_PIP" ]; then \
+	  (cd install && curl -O $(GETPIP) || \
+	  { echo "Failed on command: curl -O $(GETPIP)."; \
+	    echo "Try setting CHPL_PIP to $$(which pip) and trying again"; \
+	    exit 1; } && \
 	  export PYTHONUSERBASE=$(CHPL_VENV_INSTALL_DIR) && \
-	  $(PYTHON) get-pip.py --user) \
+	  python get-pip.py --user) \
 	fi
 
 # Install virtualenv program.
 $(CHPL_VENV_VIRTUALENV): check-exes $(PIP)
 	export PYTHONPATH="$(PIPLIBS):$$PYTHONPATH" && \
-	$(PYTHON) $(PIP) install -U --force-reinstall --ignore-installed \
+	python $(PIP) install -U --force-reinstall --ignore-installed \
 	 --prefix=$(CHPL_VENV_INSTALL_DIR) $(CHPL_PIP_INSTALL_PARAMS) $(shell cat virtualenv.txt)
 
 # Phony convenience target for installing virtualenv.
