Added a thorough check for duplicate data filenames for performance testing.  Every time a performance test is run, this check is run.  If a common output directory is being used (via CHPL_TEST_PERF_DIR as in in the nightly testing), any duplicates are treated as errors and testing stops.  Otherwise, duplicates result in warning messages.
So as to make this and any warnings more obvious, added warnings to
the testing summary line.  Unified warning messages issued by the
testing system (at least ones that I knew about) to match "^[Warning".

start_test:

- Added check for duplicate .dat filenames during performance testing
  (but not for --generate-graphs)

- Added warning messages to the test summary

- General clean up:
  - Unified warning messages
  - Removed CHPL_TEST_INVOKE_DIR (not used)
  - Removed setting of CHPL_TEST_PERF_DIR if the user did not set it
    (not needed)
  - Removed unnecessary pipes (grep | wc => grep -c)

createGraphs:

- Unified warning messages
- Improved gnuplot failure message



git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@18098 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/util/start_test b/util/start_test
--- a/util/start_test
+++ b/util/start_test
@@ -824,7 +824,6 @@ if ($comm != "none") then
 endif
 
 set invocationDir = "$cwd"
-setenv CHPL_TEST_INVOKE_DIR "$invocationDir"
 
 echo \[Starting Chapel regression tests - $datestr\] |& $tee $logtmp
 echo \[starting directory: \"$invocationDir\"] |& $tee -a $logtmp
@@ -994,15 +993,58 @@ mv $logtmp $logfile
 
 # Set up vars for performance testing/graphing
 if ($performance || $gengraphs) then
+    echo ""
+    echo "[Checking for duplicate performance data filenames]" |& tee -a $logfile
     # NOTE: this logic is currently repeated in sub_test
     if ($?CHPL_TEST_PERF_DIR) then
         set perfdir = $CHPL_TEST_PERF_DIR
     else
 	set perfdir = ./perfdat/`uname -n`
-	setenv CHPL_TEST_PERF_DIR "$perfdir"
     endif
     set createGraphs = $utildir/createGraphs
     set viewGraphs = $utildir/viewGraphs
+endif
+
+# If we are running the performance tests, then check for unique .dat
+#  filenames.  Issue a error and exit if we have specified a common
+#  common directory via CHPL_TEST_PERF_DIR otherwise issue a warning.
+# NOTE: I am not proud of having written the following.
+if ($performance) then
+    # find all the .perfkeys files and grep any .dat files names from them
+    set perffiles = `find . -name \*.perfkeys -print -exec grep "^#[[:space:]]*file:" {} \;`
+    # dummy element at the end to handle the last file
+    set perffiles = ($perffiles "file:")
+    set lastfile = "#"
+    set yucktmpfile = /tmp/$user-start_test-$$
+    touch $yucktmpfile
+    foreach pfline ($perffiles)
+        set thisfile = `basename $pfline`
+        # NOTE: this doesn't handle the case where these is no space after the :
+        if ($lastfile != "#" && $lastfile != "#file:" && $lastfile != "file:") then
+            if ($thisfile != "#" && $thisfile != "#file:") then
+                set dotdatfile = `basename $lastfile .perfkeys`
+                set basefilename = `basename $dotdatfile .dat`
+                echo $basefilename >> $yucktmpfile
+            endif
+        endif
+        set lastfile = $thisfile
+    end
+
+    set perfcount = `sort $yucktmpfile | uniq -d`
+    set duperror = 0
+    foreach token ($perfcount)
+        if ($?CHPL_TEST_PERF_DIR) then
+            echo "[Error: Duplicate performance data filenames ($token.dat)]" |& tee -a $logfile
+            set duperror = 1
+        else
+            echo "[Warning: Duplicate performance data filenames ($token.dat)]" |& tee -a $logfile
+        endif
+    end
+    rm $yucktmpfile
+    if ($duperror != 0) then
+        exit 1
+    endif
+    echo ""
 endif
 
 
@@ -1223,6 +1265,7 @@ echo " " |& $tee -a $logfile
 # Output grep to a temp file, don't want to infinite loop
 set futuremarker = "^Future"
 set errormarker = "^\[Error"
+set warningmarker = "^\[Warning"
 if ($performance == 0 && $gengraphs) then
     set successmarker = "^\[Success generating"
 else
@@ -1238,20 +1281,24 @@ echo \[Test Summary - $datestr\] |& $tee $logfile.summary
 if ($clean_only == 0) then
     grep "$errormarker" $logfile |& $tee -a $logfile.summary
     if ($suppressions != "") then
-    $utildir/filterSuppressions $suppressions $logfile.summary
+        $utildir/filterSuppressions $suppressions $logfile.summary
     endif
-    grep "$futuremarker" $logfile |& $tee -a $logfile.summary
 
-    set successes = `grep "$successmarker" $logfile | wc -l`
+    grep "$futuremarker" $logfile |& $tee -a $logfile.summary
+    grep "$warningmarker" $logfile |& $tee -a $logfile.summary
+
+    set successes = `grep -c "$successmarker" $logfile`
     set skipstdinredirs = `grep -c "$skipstdinredirectmarker" $logfile`
 
     # count failures from the summary file rather than the log file because
-    # it's already have its suppressions removed => better count
-    set failures = `grep "$errormarker" $logfile.summary | wc -l`
-    set futures = `grep "$futuremarker" $logfile | wc -l`
+    # it's already have its suppressions removed => better count (plus
+    # the summary file is smaller, so do it for the others too)
+    set failures = `grep -c "$errormarker" $logfile.summary`
+    set futures = `grep -c "$futuremarker" $logfile.summary`
+    set warnings = `grep -c "$warningmarker" $logfile.summary`
 
     if ($skipstdinredirs != 0) echo \[Skipped $skipstdinredirs tests with .stdin input\]
-    echo \[\Summary: \#Successes = $successes \| \#Failures = $failures \| \#Futures = $futures\] |& $tee -a $logfile.summary
+    echo "[Summary: #Successes = $successes | #Failures = $failures | #Futures = $futures | #Warnings = $warnings ]" |& $tee -a $logfile.summary
 else
     echo \[Summary: CLEAN ONLY\] |& $tee $logfile.summary
 endif
