Report non-zero return status of sub_test as a testing error.
This should make it easier to track down errors in testing that are
due to failing scripts.



git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@19538 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/util/start_test b/util/start_test
--- a/util/start_test
+++ b/util/start_test
@@ -1160,6 +1160,9 @@ foreach test ($testlist)
             echo "[Starting $sub_test `date`]" |& $tee -a $logfile
 
             $sub_test "$compiler" |& $tee -a $logfile
+            if ($? != 0) then
+                echo "[Error running sub_test for $test]" |& $tee -a $logfile
+            endif
 
             unsetenv CHPL_ONETEST
         endif
@@ -1279,6 +1282,9 @@ foreach testType ($testTypes)
                         echo "[Starting $sub_test `date`]" |& $tee -a $logfile
                     
                         $sub_test "$compiler" |& $tee -a $logfile
+                        if ($? != 0) then
+                            echo "[Error running sub_test in $dir]" |& $tee -a $logfile
+                        endif
                     endif
                 else
                     echo \["No tests in directory" $dir\] |& $tee -a $logfile
