Change start_test to only generate index.html if a single log directory is specified via CHPL_TEST_PERF_DIR.
git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@18883 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/util/start_test b/util/start_test
--- a/util/start_test
+++ b/util/start_test
@@ -1297,9 +1297,14 @@ foreach testType ($testTypes)
     end
 end
 
-if ($gengraphs) then
+if ($gengraphs && $?CHPL_TEST_PERF_DIR) then
     echo "[Executing viewGraphs for $graphfile in $perfdir]" |& $tee -a $logfile
     $viewGraphs "$perfdir" |& $tee -a $logfile
+    if ($? == 0) then
+        echo "[Success generating graph views in $perfdir]" |& $tee -a $logfile
+    else
+        echo "[Error generating graph views in $perfdir]" |& $tee -a $logfile
+    endif
 endif
 
 # return to where we started
