Small fixes to new performance graph tools
[reviewed by Elliot]

This patch fixes a few problems with the new performance graph tools.

- Fix date string format to one that is generally accepted (fixes
  firefox issue displaying dates in the previous century)

- Remove trailing commas in object definitions (not accepted by IE)

- Replace all the hacky calls to document.write() with cleaner
  javascript

- Add a flag --no-old-graphs to start_tests that we can use to disable
  the old-style graphs when ready

util/test/genGraphs:
- fix date string
- do not generate trailing commas
- set the document title explicitly

util/test/perf/perfgraph.js:
- set page title explicitly in the init function
- generate the suite menu in the init function

util/test/perf/index.html:
- replace calls to document.write
- use non-developer version of dygraphs

util/start_test:
- add --no-old-graphs to disable generation of old-style graphs




git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@21551 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/util/start_test b/util/start_test
--- a/util/start_test
+++ b/util/start_test
@@ -65,6 +65,7 @@
 #   -compopts  <option list>          "--cc-warnings"
 #   -execopts  <option list>          ""
 #   -launchcmd <launcher command>     ""
+#   -no-old-graphs
 #   -norecurse
 #   -comp-only
 #   -performance
@@ -654,6 +655,7 @@ set valgrind = 0
 set valgrindexe = 0
 set interpret = 0
 set performance = 0
+set oldgraphs = 1
 set gengraphs = 0
 set startdate = ""
 set testfutures = 0
@@ -755,6 +757,11 @@ while ( $#argv > 0 )
         case -generate-graphs:
                 shift
                 set gengraphs = 1
+                breaksw
+        case --no-old-graphs:
+        case -no-old-graphs:
+                shift
+                set oldgraphs = 0
                 breaksw
     case --startdate:
     case -startdate:
@@ -1182,13 +1189,15 @@ foreach test ($testlist)
             # For single tests, we only look for a $testname.graph file
             set graphfile = `basename $testname .chpl`.graph
             if (-e $graphfile) then
-                echo "[Executing createGraphs for $basedir/$graphfile in $perfdir]" |& $tee -a $logfile
-                $createGraphs "$graphfile" "$perfdir" "$startdate" |& $tee -a $logfile
-                if ($? == 0) then
-                    echo "[Success generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
-                 else
-                    echo "[Error generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
-                 endif
+                if ($oldgraphs) then
+                    echo "[Executing createGraphs for $basedir/$graphfile in $perfdir]" |& $tee -a $logfile
+                    $createGraphs "$graphfile" "$perfdir" "$startdate" |& $tee -a $logfile
+                    if ($? == 0) then
+                        echo "[Success generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
+                    else
+                        echo "[Error generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
+                    endif
+                endif
                 # new performance graph stuff
                 echo "[Executing genGraphs for $basedir/$graphfile in $perfhtmldir]" |& $tee -a $logfile
                 $createCoolerGraphs -p "$perfdir" -o "$perfhtmldir" -n "$perftestname" "$startdate_t" "$graphfile" |& $tee -a $logfile
@@ -1337,16 +1346,18 @@ foreach testType ($testTypes)
                 # generate performance graphs
                 # do this in a somewhat kludgy way to avoid stderr output
                 set graphfiles = `find . -maxdepth 1 -name \*.graph`
-                foreach gfile ($graphfiles)
-                    set graphfile = `basename $gfile`
-                    echo "[Executing createGraphs for $graphfile in $perfdir]" |& $tee -a $logfile
-                    $createGraphs "$graphfile" "$perfdir" "$startdate" |& $tee -a $logfile
-                    if ($? == 0) then
-                        echo "[Success generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
-                    else
-                        echo "[Error generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
-                    endif
-                end
+                if ($oldgraphs) then
+                    foreach gfile ($graphfiles)
+                        set graphfile = `basename $gfile`
+                        echo "[Executing createGraphs for $graphfile in $perfdir]" |& $tee -a $logfile
+                        $createGraphs "$graphfile" "$perfdir" "$startdate" |& $tee -a $logfile
+                        if ($? == 0) then
+                            echo "[Success generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
+                        else
+                            echo "[Error generating old-style graphs for $graphfile in $perfdir]" |& $tee -a $logfile
+                        endif
+                    end
+                endif
                 # new performance graph stuff
                 if (! $?CHPL_TEST_PERF_DIR && "$graphfiles" != "") then
                     echo "[Executing genGraphs for graphfiles in $dir in $perfhtmldir]" |& $tee -a $logfile
@@ -1364,12 +1375,14 @@ foreach testType ($testTypes)
 end
 
 if ($gengraphs && $?CHPL_TEST_PERF_DIR) then
-    echo "[Executing viewGraphs for $graphfile in $perfdir]" |& $tee -a $logfile
-    $viewGraphs "$perfdir" |& $tee -a $logfile
-    if ($? == 0) then
-        echo "[Success generating old-style graph views in $perfdir]" |& $tee -a $logfile
-    else
-        echo "[Error generating old-style graph views in $perfdir]" |& $tee -a $logfile
+    if ($oldgraphs) then
+        echo "[Executing viewGraphs for $graphfile in $perfdir]" |& $tee -a $logfile
+        $viewGraphs "$perfdir" |& $tee -a $logfile
+        if ($? == 0) then
+            echo "[Success generating old-style graph views in $perfdir]" |& $tee -a $logfile
+        else
+            echo "[Error generating old-style graph views in $perfdir]" |& $tee -a $logfile
+        endif
     endif
     # new performance graph stuff
     echo "[Executing genGraphs for $CHPL_HOME/test/GRAPHFILES in $perfhtmldir]" |& $tee -a $logfile
