Final two GASNet commits of the week?!?
- applied a patch developed by the GASNet team that adds
  official support for the "touch" commands that I embedded
  into our Makefile yesterday via a -T flag to Bootstrap.
  This patch also fixes a file that was missed in the
  GASNet unBootstrap script which removes all autoconf-generated
  files.  Another way that we could store our sources would be
  to untar GASNet, run unBootstrap, and commit to our repository.
  Then, when we build a release, we would run Bootstrap before
  tarring and make sure that tar preserved the file timestamps.
  I chose not to take this approach for now because it's a bigger
  change to what we've been doing and requires the use of svn:ignore
  files to ignore changes to the GASNet source tree.

- based on a conversation with Colin, moved the build
  directory for GASNet down to the third-party/gasnet
  directory rather than buried deep within the install/
  directory.  This makes it easier to blow away files
  that are unneeded after GASNet's build step via a rm -r
  on the build/ subdirectory.

I think that this wraps up all of my GASNet todo items for this
week -- both those that were anticipated and those that came up
along the way.  If you notice anything surprising about GASNet,
please report it.



git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@15360 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/third-party/gasnet/GASNet-1.12.0/Bootstrap b/third-party/gasnet/GASNet-1.12.0/Bootstrap
--- a/third-party/gasnet/GASNet-1.12.0/Bootstrap
+++ b/third-party/gasnet/GASNet-1.12.0/Bootstrap
@@ -26,8 +26,10 @@ for arg in "$@"; do
     	echo " -y  force a Bootstrap, even if it looks unnecessary"
     	echo " -n  no checks for autotool presence and versions"
 	echo " -o  Bootstrap for tools-only distribution (default is conduit-mode)"
+	echo " -T  touch Bootstrap-generated files to make them appear up-to-date"
 	exit 1
     	;;
+    -T) DOTOUCH=1 ;;
     -v) autofilter=cat ;;
     -y) CONFIRM=1 ;;
     y) CONFIRM=1 ;; # legacy
@@ -44,6 +46,26 @@ for arg in "$@"; do
     *) ;; # ignore unrecognized args
   esac
 done
+
+if [ "$DOTOUCH" = 1 ]; then
+    if [   -r $srcdir/gasnet_config.h.in \
+        -a -r $srcdir/Makefile.in \
+        -a -r $srcdir/aclocal.m4 \
+        -a -r $srcdir/configure \
+    ]; then
+        echo "Touching Bootstrap-generated files in $srcdir to make them appear up-to-date"
+        cd $srcdir
+        touch aclocal.m4
+        sleep 2
+        touch configure gasnet_config.h.in
+        sleep 2
+        perl -ane 'utime undef, undef, (grep {m/\bMakefile\.in$/ && -f $_} @F);' -- unBootstrap
+        exit 0;
+    else
+        echo "Can't touch generated files because this tree does not appear to be Bootstrapped"
+        exit 1;
+    fi
+fi
 
 DOIT='echo "+ $CMD | \$autofilter" ; ( eval $TIME $CMD 2>&1 || kill $$ ) | eval $autofilter'
 
