Revert "Modify nightly to include checkChplInstall"

diff --git a/util/test/checkChplInstall b/util/test/checkChplInstall
--- a/util/test/checkChplInstall
+++ b/util/test/checkChplInstall
@@ -66,7 +66,7 @@ fi
 CHPL_DIR=${CHPL_CHECK_INSTALL_DIR:-${HOME}/.chpl}
 if [ ! -d ${CHPL_DIR} ] ; then
     echo "${CHPL_DIR} does not exist. Creating it."
-    mkdir -p ${CHPL_DIR} || { echo "Failed to create ${CHPL_DIR}." && exit 1 ; }
+    mkdir -p ${CHPL_DIR} || { echo "Failed to create ${CHPL_DIR}." && exit 10 ; }
 fi
 
 # Location of test job
@@ -140,8 +140,6 @@ else
     echo "\$CHPL_LAUNCHER=${chpl_launcher} is not compatible with test script."
     echo "This does not necessarily indicate that your Chapel installation is incorrect."
     echo "See \$CHPL_HOME/doc/launcher.rst for information on manually launching Chapel programs."
-    # This exit code should be recognized as a failure to complete check, but
-    # not necessarily failure of build
     exit 10
 fi
 
@@ -173,9 +171,7 @@ TEST_EXEC_OUT=${TEST_JOB}.exec.out
         echo ""
         echo "== Diff Log =="
         echo "$(diff ${TEST_EXEC_OUT} ${GOOD})"
-        # This exit code should be recognized as successfully building, but
-        # with some errors
-        exit 20
+    exit 10
     fi
 )
 
