Miniscule insignificant modifications to output

diff --git a/util/test/checkChplInstall b/util/test/checkChplInstall
--- a/util/test/checkChplInstall
+++ b/util/test/checkChplInstall
@@ -28,25 +28,19 @@
 function log_info()
 {
     local msg=$@
-    echo "[INFO] ${msg}"
+    echo "[Info] ${msg}"
 }
 
 function log_warning()
 {
     local msg=$@
-    echo "[WARNING] ${msg}"
+    echo "[Warn] ${msg}"
 }
 
 function log_error()
 {
     local msg=$@
-    echo "[ERROR] ${msg}" >&2
-}
-
-function log_success()
-{
-    local msg=$@
-    echo "[SUCCESS] ${msg}"
+    echo "[Fail] ${msg}" >&2
 }
 
 # Base name for test job in examples
@@ -125,12 +119,12 @@ ${CHPL_BIN} ${TEST_DIR}/${TEST_JOB}.chpl ${COMP_FLAGS} -o ${TMP_TEST_DIR}/${TEST
 COMPILE_STATUS=$?
 if [ ${COMPILE_STATUS} -ne 0 ]; then
     log_error "Test job failed to compile - Chapel is not installed correctly"
-    log_info "Compilation output:"
+    log_error "Compilation output:"
     cat ${TMP_TEST_DIR}/${TEST_COMP_OUT}
     exit 1
 elif [ -s ${TMP_TEST_DIR}/${TEST_COMP_OUT} ]; then
     log_error "Test job compiled with output - Chapel is not installed correctly"
-    log_info "Compilation output:"
+    log_error "Compilation output:"
     cat ${TMP_TEST_DIR}/${TEST_COMP_OUT}
     exit 1
 else
@@ -182,11 +176,11 @@ TEST_EXEC_OUT=${TEST_JOB}.exec.out
 
     # Return success code (0) if diff is good
     if [ -z "${DIFF_OUTPUT}" ]; then
-    log_success "Installation works as expected!"
+    echo "SUCCESS: 'make check' passed!"
     exit 0
     else
         # Rerun test job with -v flag to help user identify discrepancy
-        log_info "There was an issue with the installation, test job output incorrect."
+        log_error "There was an issue with the installation, test job output incorrect."
         echo ""
         echo "== Verbose Test Job Execution Output =="
         ./${TEST_JOB} -nl${NUMLOCALES} ${EXEC_OPTS} -v
