Add linters-alert-failure canary
Signed-off-by: Anna Rift <anna.rift@hpe.com>

diff --git a/.github/workflows/actionlint.yml b/.github/workflows/actionlint.yml
--- a/.github/workflows/actionlint.yml
+++ b/.github/workflows/actionlint.yml
@@ -24,3 +24,15 @@ jobs:
     - name: Check workflow files
       run: ${{ steps.get_actionlint.outputs.executable }} -color
       shell: bash
+
+  # Canary for any linter failures
+  linters-alert-failure:
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    runs-on: ubuntu-latest
+    needs:
+      - actionlint
+    steps:
+      - name: Fail
+        run: |
+          echo "A required status check has failed"
+          exit 1
