Add file size check
Signed-off-by: Anna Rift <anna.rift@hpe.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -146,12 +146,27 @@ jobs:
           fetch-depth: $(( ${{github.event.pull_request.commits}} + 1 ))
       - name: check commits for large files
         run: |
-          baseSHA=${{github.event.pull_request.base.sha}}
-          headSHA=${{github.event.pull_request.head.sha}}
+          FILE_SIZE_LIMIT_KB=1024
+
           # Loop backward through commits added in the PR, starting from the
           # latest.
+          baseSHA=${{github.event.pull_request.base.sha}}
+          headSHA=${{github.event.pull_request.head.sha}}
           for commit in $(git rev-list $baseSHA..$headSHA)
           do
             echo "Current commit: $commit"
-            git diff --name-only $commit^ $commit
+            # Get list of added, copied, or modified files from this commit.
+            newFiles=$(git diff --name-status --diff-filter=ACM $commit^ $commit)
+            while read -r file; do
+              if [ "$file" = "" ]; then
+                  continue
+              fi
+              echo "Checking file: $file"
+              file_size=$(ls -l "$file" | awk '{print $5}')
+              file_size_kb=$((file_size / 1024))
+              if [ "$file_size_kb" -ge "$FILE_SIZE_LIMIT_KB" ]; then
+                echo "Error: ${file} is too large (size ${file_size_kb}KB, limit ${FILE_SIZE_LIMIT_KB}KB)."
+                exit 1
+              fi
+            done <<< "$files"
           done
