Change heartbeat logic to expect recent success or mail
Signed-off-by: Anna Rift <anna.rift@hpe.com>

diff --git a/.github/workflows/nightly-heartbeat.yml b/.github/workflows/nightly-heartbeat.yml
--- a/.github/workflows/nightly-heartbeat.yml
+++ b/.github/workflows/nightly-heartbeat.yml
@@ -43,12 +43,35 @@ jobs:
       - name: check last successful nightly run
         id: last_success
         run: |
-          last_successful=$(gh run list -w "Run nightly checks" --event schedule --status success --limit 1 --json "startedAt" --jq ".[0].startedAt" | xargs -I {} date -d {} +%s)
           current_timestamp=$(date +%s)
-          elapsed_secs=$((current_timestamp - last_successful))
           acceptable_secs=$((RECENT_NIGHTLY_JOBS_EXPECTED_HOURS * 3600))
-          if (( elapsed_secs > acceptable_secs )); then
-            echo "Warning: Last successful nightly checks run was more than $RECENT_NIGHTLY_JOB_EXPECTED_HOURS hours ago" | tee "$EMAIL_BODY_FILENAME"
+          readarray -t last_run_ids < <(gh run list -w "Run nightly checks" --event schedule --json databaseId --jq '.[].databaseId')
+          ok=false
+          for id in "${last_run_ids[@]}"; do
+            echo "- $id"
+            gh api "/repos/${{ github.repository }}/actions/runs/$id" | jq '.' | tee "run_$id.json"
+            run_timestamp=$(jq '.run_started_at | fromdate' "run_$id.json")
+            if (( run_timestamp < current_timestamp - acceptable_secs )); then
+              echo "Too old"
+              continue
+            fi
+            run_conclusion=$(jq '.conclusion' "run_$id.json")
+            if [[ "$run_conclusion" == "success" ]]; then
+              echo "Recent success"
+              ok=true
+              break
+            fi
+            gh run view "$id" --json jobs > "jobs_$id.json"
+            email_job_conclusion=$(jq '.jobs[] | select(.name == "send-failure-mail") | .conclusion' "jobs_$id.json")
+            if [[ "$email_job_conclusion" == "success" ]]; then
+              echo "Recent email sent"
+              ok=true
+              break
+            fi
+          done
+
+          if ! $ok; then
+            echo "Warning: Last nightly checks success, or failure mail send, was more than $RECENT_NIGHTLY_JOB_EXPECTED_HOURS hours ago" | tee "$EMAIL_BODY_FILENAME"
             exit 1
           fi
       - name: send warning mail
