Added another line to hpccinf.txt that can be used to specify the STREAM problem size.  Also, added a failure path in MakeAll script.
git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@16414 3a8e244f-b0f2-452b-bcba-4c88e055c3ca

diff --git a/test/studies/hpcc/Official/hpcc-1.2.0/MakeAll b/test/studies/hpcc/Official/hpcc-1.2.0/MakeAll
--- a/test/studies/hpcc/Official/hpcc-1.2.0/MakeAll
+++ b/test/studies/hpcc/Official/hpcc-1.2.0/MakeAll
@@ -21,7 +21,13 @@ do
     $DEBUG mkdir -p $BUILD_DIR/$v
     $DEBUG make arch=$v clean
     $DEBUG make arch=$v
-    $DEBUG mv hpcc $BUILD_DIR/$v
+    if [ $? != 0 ] ; then
+        echo "***"
+        echo "*** FAILED BUILD: $v"
+        echo "***"
+    else
+        $DEBUG mv hpcc $BUILD_DIR/$v
+    fi
 done
 
 echo "***"
